modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/mrbysco/padoru/issues"
license="MIT"

[[mods]]
modId="padoru"
version="${file.jarVersion}"
displayName="Padoru Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/padoru"
authors="Mrbysco"
description='''
HASHIRE SORI YO
KAZE NO YOU NI
TSUKIMIHARA WO
PADORU PADORU
'''
[[dependencies.padoru]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17.1)"
ordering="NONE"
side="BOTH"
[[dependencies.padoru]]
modId="forge"
mandatory=true
versionRange="[36.2.17,37)"
ordering="NONE"
side="BOTH"