modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/mrbysco/padoru/issues"
license="MIT"

[[mods]]
modId="padoru"
version="${file.jarVersion}"
displayName="Padoru Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/padoru"
authors="Mrbysco"
description='''
HASHIRE SORI YO
KAZE NO YOU NI
TSUKIMIHARA WO
PADORU PADORU
'''

[[dependencies.padoru]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"